hdone/objects/Address_Type__c.object
<CustomObject>
    <description>Checks to ensure both facility and provider are not populated</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <description>Type of address for the entity</description>
        <inlineHelpText>How this Provider or Facility uses this address.</inlineHelpText>
        <label>Address Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mailing - Primary</fullName>
                </value>
                <value>
                    <fullName>Mailing - Secondary</fullName>
                </value>
                <value>
                    <fullName>Home Primary</fullName>
                </value>
                <value>
                    <fullName>Home Secondary</fullName>
                </value>
                <value>
                    <fullName>Practice</fullName>
                    <default>true</default>
                    <label>Practice</label>
                </value>
                <value>
                    <fullName>Facility Address</fullName>
                </value>
                <value>
                    <fullName>Billing - Primary</fullName>
                </value>
                <value>
                    <fullName>Directory - Online</fullName>
                </value>
                <value>
                    <fullName>Directory - Print</fullName>
                </value>
                <value>
                    <fullName>Member Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Assistance</fullName>
                </value>
                <value>
                    <fullName>Hospital - Admitting Privilege</fullName>
                </value>
                <value>
                    <fullName>Hospital - Non Admitting Privilege</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address Type</label>
    <nameField>
        <displayFormat>addrtype-{00000000}</displayFormat>
        <label>AddressType Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/objects/Identifier__c.object
<CustomObject>
    <description>Generic identifier. Used to store phone numbers, email, specialties and other identifiers. These are linked to Facilities and Providers in different object.</description>
    <fields>
        <fullName>Identifier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Identifier</description>
        <inlineHelpText>Related Identifier</inlineHelpText>
        <label>Related Identifier</label>
        <referenceTo>Identifier__c</referenceTo>
        <relationshipLabel>Identifiers</relationshipLabel>
        <relationshipName>Identifiers_rel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Credential</fullName>
                </value>
                <value>
                    <fullName>Job Title</fullName>
                </value>
                <value>
                    <fullName>Language</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Information for Identifier such as email, phone, etc.</description>
        <externalId>true</externalId>
        <inlineHelpText>Value of Identifier</inlineHelpText>
        <label>Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Identifier</label>
    <nameField>
        <displayFormat>identifier-{00000000}</displayFormat>
        <label>Identifier Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/objects/Schedule__c.object
<CustomObject>
    <description>Contains schedule information for Facilities, Providers or the Address Types which is combination of a Facility or Provider and a specific address.</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Address Type</description>
        <inlineHelpText>Address and Provider or Facility associated with schedule.  Cannot edit once associated.</inlineHelpText>
        <label>Address Type</label>
        <referenceTo>Address_Type__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time for schedule</description>
        <inlineHelpText>Start time for schedule. Can edit based on picklist values. Choose a value closest to starting time.</inlineHelpText>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00:00</fullName>
                </value>
                <value>
                    <fullName>8:15:00</fullName>
                </value>
                <value>
                    <fullName>8:30:00</fullName>
                </value>
                <value>
                    <fullName>8:45:00</fullName>
                </value>
                <value>
                    <fullName>9:00:00</fullName>
                </value>
                <value>
                    <fullName>9:15:00</fullName>
                </value>
                <value>
                    <fullName>9:30:00</fullName>
                </value>
                <value>
                    <fullName>9:45:00</fullName>
                </value>
                <value>
                    <fullName>10:00:00</fullName>
                </value>
                <value>
                    <fullName>10:15:00</fullName>
                </value>
                <value>
                    <fullName>10:30:00</fullName>
                </value>
                <value>
                    <fullName>10:45:00</fullName>
                </value>
                <value>
                    <fullName>11:00:00</fullName>
                </value>
                <value>
                    <fullName>11:15:00</fullName>
                </value>
                <value>
                    <fullName>11:30:00</fullName>
                </value>
                <value>
                    <fullName>11:45:00</fullName>
                </value>
                <value>
                    <fullName>12:00:00</fullName>
                </value>
                <value>
                    <fullName>12:15:00</fullName>
                </value>
                <value>
                    <fullName>12:30:00</fullName>
                </value>
                <value>
                    <fullName>12:45:00</fullName>
                </value>
                <value>
                    <fullName>13:00:00</fullName>
                </value>
                <value>
                    <fullName>13:15:00</fullName>
                </value>
                <value>
                    <fullName>13:30:00</fullName>
                </value>
                <value>
                    <fullName>13:45:00</fullName>
                </value>
                <value>
                    <fullName>14:00:00</fullName>
                </value>
                <value>
                    <fullName>14:15:00</fullName>
                </value>
                <value>
                    <fullName>14:30:00</fullName>
                </value>
                <value>
                    <fullName>14:45:00</fullName>
                </value>
                <value>
                    <fullName>15:00:00</fullName>
                </value>
                <value>
                    <fullName>15:15:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>sch-{00000000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/objects/Schedule_Connection__c.object
<CustomObject>
    <description>Develops connection between locations that will have a schedule and the schedule development to enable many to many relationships for locations that should have a schedule.</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to address for scheduling information</description>
        <inlineHelpText>Lookup to address for scheduling information</inlineHelpText>
        <label>Address Type</label>
        <referenceTo>Address_Type__c</referenceTo>
        <relationshipLabel>Schedule Connections</relationshipLabel>
        <relationshipName>Schedule_Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Development__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to schedule development</description>
        <inlineHelpText>Select type of schedule to create by clicking the appropriate Schedule Development name.</inlineHelpText>
        <label>Schedule Development</label>
        <referenceTo>Schedule_Development__c</referenceTo>
        <relationshipLabel>Schedule Connections</relationshipLabel>
        <relationshipName>Schedule_Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Connection</label>
    <nameField>
        <displayFormat>SCHCONN-{000000}</displayFormat>
        <label>Schedule Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/objects/Schedule_Development__c.object
<CustomObject>
    <description>Used to create schedules for multiple items.</description>
    <fields>
        <fullName>MonthNumber__c</fullName>
        <description>Translates textual month into numeric. Used for Apex classes</description>
        <formula>CASE( Month__c , &quot;January&quot;, 1, 
&quot;February&quot;, 2,
&quot;March&quot;, 3,
&quot;April&quot;, 4,
&quot;May&quot;, 5,
&quot;June&quot;, 6,
&quot;July&quot;, 7,
&quot;August&quot;, 8,
&quot;September&quot;, 9,
&quot;October&quot;, 10,
&quot;November&quot;, 11,
&quot;December&quot;, 12,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Month number based on picklist value selected.</inlineHelpText>
        <label>MonthNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_Days__c</fullName>
        <description>Days that schedule should be used.</description>
        <inlineHelpText>Days that schedule should be used.</inlineHelpText>
        <label>Scheduled Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YearNumber__c</fullName>
        <formula>If( ISNUMBER(TEXT( Year__c )) ,  VALUE(TEXT( Year__c )) , Null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YearNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Schedule Development</label>
    <nameField>
        <displayFormat>SCHD-{000000}</displayFormat>
        <label>Schedule Development Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/classes/TestFactory.cls
@isTest
public class TestFactory {
    
    // Build Identifier
    public static Identifier__c buildIdentifier(String testingtype, String idvalue) {
        Identifier__c testidentifier = new Identifier__c();
        testidentifier.Value__c = idvalue;
        testidentifier.Type__c = testingtype;
        return testidentifier;
    }
    //Create 200 Schedule Connections
    @isTest
    public static List<Schedule__c> createSchedules(){
        
        Integer schcount = 1;
       // try{ 
            //Create list of 200 bulk Schedules
            List<Schedule__c> testschedules = Test.loadData(Schedule__c.sObjectType, 'testSchedules');
            System.assertEquals(testschedules.size(),200);
            If (testschedules.isEmpty() == False){
                return testschedules;    
                System.debug('Schedule List size is '+testschedules.size());
            } else{
                System.debug('Schedule list is empty.');
                return null;
            }
        //} catch (ListException e){
       // }
        return null;
    }
    
    
    //Create 200 Schedules
    @isTest
    public static List<Schedule__c> createBulkSchedules(){
        
        //Create list of 200 bulk AddressTypes. Needed to create schedules
      //  try{            
            List<Schedule_Connection__c> testschconn = createBulkScheduleConnections();
            System.assertEquals(testschconn.size(),200);
            
            If (testschconn.isEmpty() == False){
                insert testschconn;
                List<Schedule__c> testbulksch = new List<Schedule__c>();
                List<String> daysList = new List <String>();
                List<date> dates = new List <date>();
                
                If (testschconn.size() + Limits.getDMLRows() > Limits.getLimitDMLRows()){
                    System.debug('Need to stop processing to avoid hitting a governor limit. Too many Schedule Connection items to update in this trigger');
                    System.debug('Trying to update ' + testschconn.size() + ' Schedule Connection items but governor limits will only allow ' +  Limits.getLimitDMLRows());
                    
                    For (Schedule_Connection__c schconn : testschconn)
                        schconn.addError('You are attempting to update too many Schedule Connection items at once. Please try again with fewer records.');
                }else
                {
                    System.debug('Continue processing. Not going to hit governor limits for Schedule Connection records');
                    System.debug('Going to update ' + testschconn.size() + ' Schedule Connection items and governor limits will allow ' + Limits.getLimitDMLRows());
                    
                    For (Schedule_Connection__c s : testschconn) {
                        daysList.clear();   // Start new list of days
                        dates.clear();      // Clear dates List
                        //**Not working     daysList.addall(s.Schedule_Development__r.Scheduled_Days__c.split(';')); // Splits multi select picklist for days
                        // Add all multi select picklist days
                        For (String day:daysList){
                            //    dates.addall(myDateClass.getMyDates(day,s.Schedule_Development__r.MonthNumber__c.intvalue(),s.Schedule_Development__r.YearNumber__c.intvalue()));
                        }
                        
                        // Check Apex limits before processing
                        If (dates.size() + Limits.getDMLRows() > Limits.getLimitDMLRows()){
                            System.debug('Need to stop processing to avoid hitting a governor limit. Too many Date items to update in this trigger');
                            System.debug('Trying to update ' + dates.size() + ' Date items but governor limits will only allow ' +  Limits.getLimitDMLRows());
                            
                            For(date d:dates)
                                s.addError('You are attempting to update too many Date items at once. Please try again with fewer records.');
                        }else
                        {
                            System.debug('Continue processing. Not going to hit governor limits for date records');
                            System.debug('Going to update ' + dates.size() + ' date items and governor limits will allow ' + Limits.getLimitDMLRows());
                            
                            For(date d:dates){
                                testbulksch.add(new Schedule__c(
                                    Address_Type__c = s.Address_Type__c,
                                    Start_Time__c = s.Schedule_Development__r.Start_Time__c,
                                    End_Time__c = s.Schedule_Development__r.End_Time__c,
                                    Start_Date__c = d));
                            }
                        }
                    }
                    System.debug(Logginglevel.ERROR, 'Number of schedules created ' + testbulksch.size());
                    return testbulksch;
                    System.debug('Final number of script statements used so far : ' + Limits.getDMLStatements());
                    System.debug('Final heap size: ' + Limits.getHeapSize());
                }
            } else{
                System.debug('Error list is empty.');
                return null;
            }
        //}catch (ListException e){
        //}
        return null;
    }
    
    
    //Create 200 Schedule Connections
    @isTest
    public static List<Schedule_Connection__c> createBulkScheduleConnections(){
        
        Integer schcount = 1;
        String prodname = 'MemberOne';
       // try{ 
            //Create list of 200 bulk AddressTypes
            List<Address_Type__c> testbulkaddrtypes = createBulkAddressType();
            System.assertEquals(testbulkaddrtypes.size(),200);
            
            //Create list of 200 bulk Schedule Development records
            List<Schedule_Development__c> testbulkschdev = createBulkScheduleDevelopment();
            System.assertEquals(testbulkschdev.size(),200);
            
            //Create list of 200 Audit Setting Records
            List<AuditSetting__c> testbulkaudset = createBulkAuditSetting();
            System.assertEquals(testbulkaudset.size(),200);
            
            If (testbulkaddrtypes.isEmpty() == False &&
                testbulkschdev.isEmpty() == False){
                    List<Schedule_Connection__c> testbulkschconn = new List<Schedule_Connection__c>();
                    For (Integer I = 0 ; I < testbulkaddrtypes.size(); I++){
                        testbulkschconn.add(new Schedule_Connection__c(Address_Type__c = testbulkaddrtypes.get(I).id,
                                                                       Schedule_Development__c = testbulkschdev.get(I).id,
                                                                       AuditSetting__c = testbulkaudset.get(I).id,
                                                                       Product_Name__c = prodname
                                                                      ));
                    }
                    return testbulkschconn;    
                    System.debug('Bulk Schedule Connection size is '+testbulkschconn.size());
                } else{
                    System.debug('Error list is empty.');
                    return null;
                }
        //} catch (ListException e){
       // }
        return null;
    }
    
    // Helper method to create Bulk Addresses    
    @isTest
    public static List<Address__c> createBulkAddress(){
        
        //try{
            // Creates bulk Addresses. Uses Static Resource data file
            List<Address__C> testbulkaddr = Test.loadData(Address__c.sObjectType, 'testAddresses');
            System.assertEquals(testbulkaddr.size(),200);
            
            If (testbulkaddr.isEmpty()== False){
                System.debug('16.Number of Queries used in this apex code so far: ' + Limits.getQueries());
                System.debug('17.Number of rows queried in this apex code so far: ' + Limits.getDmlRows());
                System.debug('18. Number of script statements used so far : ' +  Limits.getDmlStatements());
                System.debug('19.Number of Queries used in this apex code so far: ' + Limits.getQueries());
                System.debug('20.Number of rows queried in this apex code so far: ' + Limits.getDmlRows());
                update testbulkaddr;
                return testbulkaddr;
                System.debug('Bulk address size is '+testbulkaddr.size());
            } else {
                System.debug('Error list is empty. Size of testbulkaddr is '+ testbulkaddr.size());
                return null;
            }
        //} catch (ListException e){
        //}
        return null;
    }
    
    //Creates bulk contacts
    @isTest
    public static List <Contact> createBulkContacts(){
        
        //try{
            // Creates bulk Contacts. Uses Static Resource data file
            List<Contact> testbulkcontact = Test.loadData(Contact.sObjectType, 'testProviders');
            System.assertEquals(testbulkcontact.size(),200);
            
            If (testbulkcontact.isEmpty()== False){
                //update testbulkcontact;
                return testbulkcontact;
                System.debug('Bulk Contact size '+testbulkcontact.size());
                
            } else {
                System.debug('Error list is empty. Size of testbulkcontact is '+ testbulkcontact.size());
                return null;
            }
       // } catch (ListException e){
        //}
        return null;
    }
    
    
    // Helper method to create bulk Address Types. Passes in values from other helper methods    
    @isTest
    public static List <Address_Type__c> createBulkAddressType(){
       // try{
            // Creates bulk Addresses. Uses Static Resource data file
            List<Address__C> testbulkaddr = createBulkAddress();
            System.assertEquals(testbulkaddr.size(),200);
            
            // Create list of bulk Contacts
            List<Contact> testbulkcontacts = createBulkContacts();
            System.assertEquals(testbulkcontacts.size(),200);
            
            If (testbulkaddr.isEmpty()== False &&
                testbulkcontacts.isEmpty()==False){
                    
                    List<Address_Type__c> testbulkaddrtype = new List<Address_Type__c>();
                    For (Integer I = 0 ; I < testbulkcontacts.size(); I++){
                        testbulkaddrtype.add(new Address_Type__c(Provider__c = testbulkcontacts.get(I).id,
                                                                 Address__c = testbulkaddr.get(I).id,
                                                                 Active__c = True));
                    }
                    insert testbulkaddrtype;
                    return testbulkaddrtype;
                    system.debug('address type size ' + testbulkaddrtype.size());
                } else {
                    System.debug('Error list is empty. Size of testbulkaddr is '+ testbulkaddr.size());
                    return null;
                }
       // } catch (ListException e){
       // }
        return null;
    }        
    @isTest
    public static List<Schedule_Development__c> createBulkScheduleDevelopment(){
        
      //  try{
            List<Schedule_Development__c> testbulkschdev = Test.loadData(Schedule_Development__c.sObjectType, 'testScheduleDevelopment');
            System.assertEquals(testbulkschdev.size(),200);
            
            if (testbulkschdev.isEmpty()== False){
                //   update testbulkschdev;
                return testbulkschdev;
            } else {
                System.debug('Error list is empty. Size of Schedule Development file is '+ testbulkschdev.size());
                return null;
            }
       // } catch (ListException e){
       // }
       return null;
    }
    @isTest
    public static List<AuditSetting__c> createBulkAuditSetting(){
        
       // try{
            List<AuditSetting__c> testbulkaudset = Test.loadData(AuditSetting__c.sObjectType, 'testAuditSettings');
            System.assertEquals(testbulkaudset.size(),200);
            
            if (testbulkaudset.isEmpty()== False){
                //   update testbulkaudset;
                return testbulkaudset;
            } else {
                System.debug('Error list is empty. Size of Audit Setting file is '+ testbulkaudset.size());
                return null;
            }
        //} catch (ListException e)
        //{
        return null;
    }
}