hdone/objects/Schedule__c.object
<CustomObject>
    <description>Contains schedule information for Facilities, Providers or the Address Types which is combination of a Facility or Provider and a specific address.</description>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>End Date and Time for Schedule item. Combines date and time entered.</description>
        <inlineHelpText>End Date and Time for Schedule item. Combines end date and end time entered. Cannot edit field.</inlineHelpText>
        <label>EndDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <description>Ending date for schedule item</description>
        <inlineHelpText>Ending date for schedule item. Auto populated from Start Date. Cannot currently edit.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Ending time for schedule item</description>
        <inlineHelpText>End time for schedule. Can edit based on picklist values. Choose a value closest to ending time.</inlineHelpText>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00:00</fullName>
                </value>
                <value>
                    <fullName>8:15:00</fullName>
                </value>
                <value>
                    <fullName>8:30:00</fullName>
                </value>
                <value>
                    <fullName>8:45:00</fullName>
                </value>
                <value>
                    <fullName>9:00:00</fullName>
                </value>
                <value>
                    <fullName>9:15:00</fullName>
                </value>
                <value>
                    <fullName>9:30:00</fullName>
                </value>
                <value>
                    <fullName>9:45:00</fullName>
                </value>
                <value>
                    <fullName>10:00:00</fullName>
                </value>
                <value>
                    <fullName>10:15:00</fullName>
                </value>
                <value>
                    <fullName>10:30:00</fullName>
                </value>
                <value>
                    <fullName>10:45:00</fullName>
                </value>
                <value>
                    <fullName>11:00:00</fullName>
                </value>
                <value>
                    <fullName>11:15:00</fullName>
                </value>
                <value>
                    <fullName>11:30:00</fullName>
                </value>
                <value>
                    <fullName>11:45:00</fullName>
                </value>
                <value>
                    <fullName>12:00:00</fullName>
                </value>
                <value>
                    <fullName>12:15:00</fullName>
                </value>
                <value>
                    <fullName>12:30:00</fullName>
                </value>
                <value>
                    <fullName>12:45:00</fullName>
                </value>
                <value>
                    <fullName>13:00:00</fullName>
                </value>
                <value>
                    <fullName>13:15:00</fullName>
                </value>
                <value>
                    <fullName>13:30:00</fullName>
                </value>
                <value>
                    <fullName>13:45:00</fullName>
                </value>
                <value>
                    <fullName>14:00:00</fullName>
                </value>
                <value>
                    <fullName>14:15:00</fullName>
                </value>
                <value>
                    <fullName>14:30:00</fullName>
                </value>
                <value>
                    <fullName>14:45:00</fullName>
                </value>
                <value>
                    <fullName>15:00:00</fullName>
                </value>
                <value>
                    <fullName>15:15:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>Start Date and Time for Schedule item. Combines date and time entered.</description>
        <inlineHelpText>Start Date and Time for Schedule item. Combines start date and start time entered. Cannot edit field.</inlineHelpText>
        <label>StartDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Start date of schedule</description>
        <inlineHelpText>Start date of schedule item. Can edit if date needs to be changed.  Date must be today or in future, cannot change to a date in past.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time for schedule</description>
        <inlineHelpText>Start time for schedule. Can edit based on picklist values. Choose a value closest to starting time.</inlineHelpText>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00:00</fullName>
                </value>
                <value>
                    <fullName>8:15:00</fullName>
                </value>
                <value>
                    <fullName>8:30:00</fullName>
                </value>
                <value>
                    <fullName>8:45:00</fullName>
                </value>
                <value>
                    <fullName>9:00:00</fullName>
                </value>
                <value>
                    <fullName>9:15:00</fullName>
                </value>
                <value>
                    <fullName>9:30:00</fullName>
                </value>
                <value>
                    <fullName>9:45:00</fullName>
                </value>
                <value>
                    <fullName>10:00:00</fullName>
                </value>
                <value>
                    <fullName>10:15:00</fullName>
                </value>
                <value>
                    <fullName>10:30:00</fullName>
                </value>
                <value>
                    <fullName>10:45:00</fullName>
                </value>
                <value>
                    <fullName>11:00:00</fullName>
                </value>
                <value>
                    <fullName>11:15:00</fullName>
                </value>
                <value>
                    <fullName>11:30:00</fullName>
                </value>
                <value>
                    <fullName>11:45:00</fullName>
                </value>
                <value>
                    <fullName>12:00:00</fullName>
                </value>
                <value>
                    <fullName>12:15:00</fullName>
                </value>
                <value>
                    <fullName>12:30:00</fullName>
                </value>
                <value>
                    <fullName>12:45:00</fullName>
                </value>
                <value>
                    <fullName>13:00:00</fullName>
                </value>
                <value>
                    <fullName>13:15:00</fullName>
                </value>
                <value>
                    <fullName>13:30:00</fullName>
                </value>
                <value>
                    <fullName>13:45:00</fullName>
                </value>
                <value>
                    <fullName>14:00:00</fullName>
                </value>
                <value>
                    <fullName>14:15:00</fullName>
                </value>
                <value>
                    <fullName>14:30:00</fullName>
                </value>
                <value>
                    <fullName>14:45:00</fullName>
                </value>
                <value>
                    <fullName>15:00:00</fullName>
                </value>
                <value>
                    <fullName>15:15:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>sch-{00000000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hdone/classes/CalcSchDate.cls
global without sharing class CalcSchDate{
    /* List to get DateTime from Date and picklist time inputs
     * Takes collection variable from Flow for processing
     */
    @InvocableMethod(label='Compute datetime' description='Computes date time from text values')
    
    global static list<String> getMyDates(List<List<Schedule__c>> sobjsch){
         
        Integer size = sobjsch.size();
        System.assert(size > 0, 'Schedule List is empty');
        System.debug('Size of Schedule List should be 1 because List of Lists. Value is ' + sobjsch.size());
        
        List<Schedule__c> schUpdate = new List<Schedule__c>{};
            For (List<Schedule__c> innerloop : sobjsch){
                for(Schedule__c schedule : innerloop){
                    schedule.StartDateTime__c = getDateTime(schedule.Start_Date__c,schedule.Start_Time__c);
                    schedule.EndDateTime__c = getDateTime(schedule.End_Date__c,schedule.End_Time__c);
                    schUpdate.add(schedule);
                }
            }
        
        update schUpdate;
        return null;
    }
    
    //======================================================//
    //Compute and Populate Date Time in Start and End Time field values
    //======================================================//
    public static DateTime getDateTime(Date s,String dtTime) {
      if(s != null && dtTime != null){
        return Datetime.valueOf(s.year()+ '-' + s.month() 
                               + '-' + s.day() + ' ' + dtTime);
      }
      return DateTime.newInstance(1900,1,1);
    }   
}